# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 6 # it will paginate after this number
language: "en-us"
words_per_minute: 200

# Base configs
baseurl: /
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-4727807-2"

# UI configs
title: "IG Photography"
subtitle: "See the world through my eyes!"
author: "Indra Gunawan"
header:
  title: "Photography"
  subtitle: "by Indra Gunawan"
footer:
  name: "Hey there, my name is Indra"
  bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
  github: 'Want a website like this for yourself for free? Just <a href="https://github.com/ramswaroop/photography">fork this repo on github</a> ;)'
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/feedsbrain"
  instagram: "https://www.instagram.com/indragunawandotcom"
  dribbble:
  linkedin: "https://in.linkedin.com/in/feedsbrain"
  github: "https://www.github.com/feedsbrain"

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: feedsbrain
repo: photography
branch: master
relative_source: ../photography/
destination: ./_site/
# for sitemap plugin
url: https://photos.indragunawan.com
# for jekyll
production_url: https://photos.indragunawan.com/
source_url: https://github.com/feedsbrain/photography/
# for deployment
git_name: Indra Gunawan
git_email: feedsbrain@gmail.com

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
