name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Build and deploy with rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake site:deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
